[PLATFORM-379]: [Localauth0] Add simple frontend
primait/localauth0 pull request #2
Opened 2022-04-04 10:53 UTC by cottinisimone

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-379

2022-04-07 08:19 UTC, matteosister submitted a review, later dismissed
love this! :love_you_gesture:

2022-04-07 10:17 UTC, emanuelemacri commented on web/assets/scss/style.scss
> +}
Questo può andare via, poi please formattate i css/scss con 2 spaziature e non :D

2022-04-07 10:21 UTC, emanuelemacri commented on web/src/model.rs
> +                        </legend>
Manca un div con la colonna prima del `legend` e l'`addon` andrebbe usata sempre prima del titolo
```suggestion
                        <div class="form-grid__row__column">
                            <legend class="form-legend">
                                <span class="form-legend__addon">
                                    <img
                                        src="assets/static/media/localauth0.png"
                                        width="80"
                                        height="80"
                                        alt="Localauth0 logo"
                                    />
                                </span>
                                <span class="form-legend__title">{"LOCALAUTH0"}</span>
                            </legend>
                        </div>
```

2022-04-07 10:27 UTC, emanuelemacri commented on web/src/model.rs
> +                    </div>
Anche qui manca una colonna e il `button-row` (so che l'avete levato per mettere il bottone centrale a tutta larghezza, ma provate così:

```suggestion
                    <div class="form-grid__row form-grid__row--small">
                        <div class="form-grid__row__column">
                            <div class="button-row button-row--center">
                                <button />
                            </div>
                        </div>
                    </div>
```

Nel `main.scss` aggiungete pure una classe `.button-row--center`, poi la faremo anche noi 👍 

```
.button-row--center {
  justify-content: center;
}

2022-04-07 10:30 UTC, emanuelemacri commented on web/src/model.rs
> +                        <div aria-hidden="false" aria-label="Button" class="icon icon--size-s" role="img">
Errore mio di quando vi ho mandato il codice
```suggestion
                        <div aria-hidden="false" aria-label="Add permission" class="icon icon--size-l" role="img">
```

2022-04-07 10:31 UTC, emanuelemacri commented on web/src/model.rs
> +                        <div aria-hidden="false" aria-label="Button" class="icon icon--size-s" role="img">
idem
```suggestion
                        <div aria-hidden="false" aria-label="Remove permission" class="icon icon--size-l" role="img">
```

2022-04-07 10:45 UTC, emanuelemacri requested changes
Ultima cossetta, poi tutto ok

2022-04-07 10:45 UTC, emanuelemacri commented on web/assets/scss/style.scss
>  }
Aggiungi pure qui per ora questa, poi tutto ok!
```
.button-row--center {
  justify-content: center;
}
```

2022-04-08 09:30 UTC, emanuelemacri approved these changes
🚀

2022-04-08 09:31 UTC, merged